# Generated by Django 5.0.13 on 2025-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(default='37', max_length=10),
            preserve_default=False,
        ),
    ]
