# Generated by Django 5.0.13 on 2025-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_country_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
