# Generated by Django 5.0.13 on 2025-06-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_wompi_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('EXPIRED', 'Expirado'), ('CHECKED_OUT', 'Convertido en orden'), ('FINISHED', 'Finalizado')], default='OPEN', max_length=20),
        ),
    ]
