# Generated by Django 5.0.13 on 2025-07-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hook_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
