# Generated by Django 5.0.13 on 2025-03-18 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la marca')),
                ('slug_name', models.SlugField(max_length=40, unique=True, verbose_name='Slug de la marca')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la marca')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la categoría')),
                ('slug_name', models.SlugField(max_length=40, unique=True, verbose_name='Slug de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la categoría')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('slug_name', models.SlugField(max_length=40, unique=True, verbose_name='Slug de la categoría')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del producto')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock del producto')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product SKU')),
                ('is_available', models.BooleanField(default=True, verbose_name='Producto disponible')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Calificación del producto')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('percentage_discount', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de descuento')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
