# Generated by Django 5.0.13 on 2025-03-25 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockBySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('size', models.CharField(max_length=10, verbose_name='Talla')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_by_size', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock por talla',
                'verbose_name_plural': 'Stock por tallas',
            },
        ),
    ]
