# Generated by Django 5.0.13 on 2025-04-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productstockbysize'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False, verbose_name='Más vendidos'),
        ),
        migrations.AddField(
            model_name='product',
            name='newcomers',
            field=models.BooleanField(default=False, verbose_name='Recién llegados'),
        ),
    ]
