# Generated by Django 5.0.13 on 2025-04-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='selecciona esta casilla si es la imagen principal del producto'),
        ),
    ]
