# Generated by Django 5.0.13 on 2025-04-24 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_produccomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducComment',
            new_name='ProductComment',
        ),
    ]
