# Generated by Django 5.0.13 on 2025-04-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_produccomment_productcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-modified'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'Comentario del producto', 'verbose_name_plural': 'comentarios del producto'},
        ),
        migrations.AddField(
            model_name='productcomment',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
    ]
