# Generated by Django 5.0.13 on 2025-04-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_options_alter_productcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes del producto'),
        ),
    ]
