# Generated by Django 5.0.13 on 2025-04-29 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_remove_user_name_user_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be entered in the format +99999999999', regex='\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
