# Generated by Django 5.0.13 on 2025-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_used',
            field=models.BooleanField(default=False, verbose_name='Ya uso el descuento de registro?'),
        ),
    ]
