# Generated by Django 5.0.13 on 2025-05-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userpromotioncode_is_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpromotioncode',
            options={'verbose_name': 'Código de usuario', 'verbose_name_plural': 'Codigos de usuario'},
        ),
    ]
